extends Node

enum FILE{OGG}
enum UI_INDICATOR_TYPE {BEAT,HALF_BEAT,THIRD_BEAT,QUARTER_BEAT,SIXTH_BEAT,EIGHTH_BEAT} 

enum NOTE{Z,X,C,V}

enum TOOL{SELECT,MARQUEE,VOICE,HORNY,MODIFY}

enum ASSET{IMAGE,AUDIO}
